[package]
name = "fanboy_exporter"
version = "0.1.0"
edition = "2021"

[dependencies]
git-version = "0.3.5"
prometheus_exporter = "0.8"
prometheus = "0.13.1"
env_logger = "0.9"
clap = "2.0"
log = "0.4"
serialport = "4.1.0"
byteorder = "1.4.3"